# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  kafka:
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Memory settings
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
      # Memory optimization configs
      - KAFKA_CFG_LOG_CLEANER_DEDUPE_BUFFER_SIZE=8388608
      - KAFKA_CFG_LOG_CLEANER_THREADS=1
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=1048576
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_CFG_NUM_NETWORK_THREADS=2
      - KAFKA_CFG_NUM_IO_THREADS=2
      - KAFKA_CFG_LOG_SEGMENT_BYTES=536870912
      # Auto topic creation 
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  kafka_data:
    driver: local